const bcrypt = require('bcryptjs');
const { Op } = require('sequelize');
const { User, Wallet } = require('../models');
const generateReferralCode = require('../utils/generateReferralCode');
const generatePassword = require('../utils/generatePassword');
const { sendAssociateCredentials } = require('../services/emailService');

// @desc Get all users (filter by role via query ?role=client/associate)
// @route GET /api/users
const getUsers = async (req, res, next) => {
  try {
    const { role, status, kyc_status, search } = req.query;
    const where = {};
    if (role) where.role = role;
    if (status) where.status = status;
    if (kyc_status) where.kyc_status = kyc_status;
    if (search) {
      where[Op.or] = [
        { name: { [Op.like]: `%${search}%` } },
        { email: { [Op.like]: `%${search}%` } },
        { phone: { [Op.like]: `%${search}%` } },
        { login_id: { [Op.like]: `%${search}%` } }
      ];
    }

    const users = await User.findAll({
      where,
      attributes: { exclude: ['password'] },
      order: [['createdAt', 'DESC']]
    });

    res.json({ success: true, count: users.length, data: users });
  } catch (error) {
    next(error);
  }
};

// @desc Get single user
// @route GET /api/users/:id
const getUser = async (req, res, next) => {
  try {
    const user = await User.findByPk(req.params.id, {
      attributes: { exclude: ['password'] },
      include: [
        { model: User, as: 'referrer', attributes: ['id', 'name', 'email'] },
        { model: User, as: 'referrals', attributes: ['id', 'name', 'email', 'role'] },
        { model: Wallet, as: 'wallet' }
      ]
    });
    if (!user) return res.status(404).json({ success: false, message: 'User not found' });
    res.json({ success: true, data: user });
  } catch (error) {
    next(error);
  }
};

// @desc Create user (Admin adds a user manually)
// @route POST /api/users
const createUser = async (req, res, next) => {
  try {
    const { name, email, phone, password, role, referred_by, pan_number, aadhar_number, referral_commission_percent } = req.body;

    // PAN & Aadhar are mandatory ONLY for associates (fraud prevention, per business requirement)
    if (role === 'associate') {
      if (!pan_number || !aadhar_number) {
        return res.status(400).json({ success: false, message: 'PAN number and Aadhar number are mandatory for Associates' });
      }
    }

    const existingPhone = await User.findOne({ where: { phone } });
    if (existingPhone) return res.status(400).json({ success: false, message: 'Phone number already exists' });

    if (email) {
      const existingEmail = await User.findOne({ where: { email } });
      if (existingEmail) return res.status(400).json({ success: false, message: 'Email already exists' });
    }

    // Associates: password is ALWAYS auto-generated by the system (admin does
    // not need to type one), and commission is fixed at 5% unless the admin
    // explicitly overrides it in the form.
    const isAssociate = role === 'associate';
    const plainPassword = isAssociate ? generatePassword() : (password || '123456');
    const hashedPassword = await bcrypt.hash(plainPassword, 10);
    const referral_code = generateReferralCode(name);

    const user = await User.create({
      name, email: email || null, phone,
      password: hashedPassword,
      plain_password: plainPassword,
      role: role || 'client',
      referred_by: referred_by || null,
      referral_commission_percent: isAssociate
        ? (referral_commission_percent || referral_commission_percent === 0 ? referral_commission_percent : 5)
        : (referral_commission_percent || null),
      pan_number: pan_number || null,
      aadhar_number: aadhar_number || null,
      referral_code,
      kyc_status: isAssociate ? 'approved' : 'not_submitted' // Admin-created associates are auto-approved
    });

    // Auto-generate login_id (DEV-XXXX)
    const login_id = `DEV-${String(user.id).padStart(4, '0')}`;
    await user.update({ login_id });

    await Wallet.create({ user_id: user.id, balance: 0 });

    let emailSent = false;
    if (isAssociate) {
      const emailResult = await sendAssociateCredentials(user, plainPassword);
      emailSent = !!(emailResult && emailResult.success && !emailResult.mock);
    }

    const { password: _, ...userData } = user.toJSON();
    res.status(201).json({
      success: true,
      data: userData,
      // Only meaningful when isAssociate — lets the admin panel show/copy
      // the auto-generated password right after creating an Associate.
      generatedPassword: isAssociate ? plainPassword : undefined,
      emailSent
    });
  } catch (error) {
    next(error);
  }
};

// @desc Update user
// @route PUT /api/users/:id
const updateUser = async (req, res, next) => {
  try {
    const user = await User.findByPk(req.params.id);
    if (!user) return res.status(404).json({ success: false, message: 'User not found' });

    const { name, email, phone, role, status, referred_by, pan_number, aadhar_number, referral_commission_percent } = req.body;
    await user.update({
      name: name ?? user.name,
      email: email !== undefined ? (email || null) : user.email,
      phone: phone ?? user.phone,
      role: role ?? user.role,
      status: status ?? user.status,
      referred_by: referred_by !== undefined ? (referred_by || null) : user.referred_by,
      pan_number: pan_number !== undefined ? pan_number : user.pan_number,
      aadhar_number: aadhar_number !== undefined ? aadhar_number : user.aadhar_number,
      referral_commission_percent: referral_commission_percent !== undefined ? referral_commission_percent : user.referral_commission_percent
    });

    const { password, ...userData } = user.toJSON();
    res.json({ success: true, data: userData });
  } catch (error) {
    next(error);
  }
};

// @desc Delete user
// @route DELETE /api/users/:id
const deleteUser = async (req, res, next) => {
  try {
    const user = await User.findByPk(req.params.id);
    if (!user) return res.status(404).json({ success: false, message: 'User not found' });
    await user.destroy();
    res.json({ success: true, message: 'User deleted successfully' });
  } catch (error) {
    next(error);
  }
};

// @desc Update KYC status
// @route PUT /api/users/:id/kyc
const updateKycStatus = async (req, res, next) => {
  try {
    const { kyc_status } = req.body; // approved / rejected
    const user = await User.findByPk(req.params.id);
    const updates = { kyc_status };
    if (kyc_status === 'approved' && !user.login_id) {
      updates.login_id = `DEV-${String(user.id).padStart(4, '0')}`;
    }
    await user.update(updates);
    res.json({ success: true, message: `KYC ${kyc_status}`, data: user });
  } catch (error) {
    next(error);
  }
};

// @desc Toggle block/unblock
// @route PUT /api/users/:id/status
const toggleUserStatus = async (req, res, next) => {
  try {
    const user = await User.findByPk(req.params.id);
    if (!user) return res.status(404).json({ success: false, message: 'User not found' });

    user.status = user.status === 'active' ? 'blocked' : 'active';
    await user.save();

    res.json({ success: true, message: `User is now ${user.status}`, data: user });
  } catch (error) {
    next(error);
  }
};

// @desc Get referral tree of an associate
// @route GET /api/users/:id/referral-tree
const getReferralTree = async (req, res, next) => {
  try {
    const referrals = await User.findAll({
      where: { referred_by: req.params.id },
      attributes: { exclude: ['password'] }
    });
    res.json({ success: true, data: referrals });
  } catch (error) {
    next(error);
  }
};

// @desc  Approve a pending associate registration (admin action)
// @route POST /api/users/:id/approve
const approveAssociate = async (req, res, next) => {
  try {
    const user = await User.findByPk(req.params.id);
    if (!user) return res.status(404).json({ success: false, message: 'User not found' });
    if (user.role !== 'associate') {
      return res.status(400).json({ success: false, message: 'Only associate registrations can be approved' });
    }

    await user.update({ 
      kyc_status: 'approved', 
      status: 'active',
      approved_by: req.user.id,
      approved_at: new Date()
    });

    // Ensure login_id is set if not already
    if (!user.login_id) {
      const login_id = `DEV-${String(user.id).padStart(4, '0')}`;
      await user.update({ login_id });
    }

    const { password, ...userData } = user.toJSON();
    res.json({ success: true, message: `Associate ${user.name} has been approved and can now login.`, data: userData });
  } catch (error) {
    next(error);
  }
};

// @desc Reject a pending associate registration (admin action)
// @route POST /api/users/:id/reject
const rejectAssociate = async (req, res, next) => {
  try {
    const user = await User.findByPk(req.params.id);
    if (!user) return res.status(404).json({ success: false, message: 'User not found' });
    
    const { rejection_reason } = req.body;
    await user.update({
      status: 'blocked',
      kyc_status: 'rejected',
      rejection_reason
    });

    res.json({ success: true, message: `Associate ${user.name} rejected.` });
  } catch (error) {
    next(error);
  }
};

// @desc Generate a JWT to login as a specific user (Admin impersonation)
// @route POST /api/users/:id/impersonate
const generateToken = require('../utils/generateToken');
const impersonateUser = async (req, res, next) => {
  try {
    const user = await User.findByPk(req.params.id);
    if (!user) return res.status(404).json({ success: false, message: 'User not found' });
    if (user.role === 'admin') {
      return res.status(403).json({ success: false, message: 'Cannot impersonate another admin' });
    }

    // Generate JWT with standard user ID payload
    // To identify it as an impersonation token, we could inject impersonated_by, but standard generateToken only takes userId.
    // Instead we'll use a custom jsonwebtoken sign here to include the impersonator.
    const jwt = require('jsonwebtoken');
    const token = jwt.sign(
      { id: user.id, impersonated_by: req.user.id },
      process.env.JWT_SECRET || 'devojas_secret_123', // matching standard token generation
      { expiresIn: '1h' } // Short lived
    );

    res.json({ 
      success: true, 
      token,
      user: {
        id: user.id,
        login_id: user.login_id,
        name: user.name,
        role: user.role
      }
    });
  } catch (error) {
    next(error);
  }
};

module.exports = {
  getUsers, getUser, createUser, updateUser, deleteUser,
  updateKycStatus, toggleUserStatus, getReferralTree, 
  approveAssociate, rejectAssociate, impersonateUser
};
